name: Build Kernel
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Kernel Source
      uses: actions/checkout@v4
      with:
        ref: sky-t-oss

    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc kmod cpio flex bison libssl-dev libelf-dev clang lld llvm git wget crossbuild-essential-arm64

    - name: Clone Official Clang Toolchain
      run: |
        # سحب الـ Clang المتوافق بالملي عبر الـ Git المباشر والسريع
        git clone --depth=1 https://github.com/YuuNoa/prebuilts_clang_host_linux-x86_clang-r450784d.git $GITHUB_WORKSPACE/clang

    - name:
